[14.0] Migrate mail modules
novacode-nl/odoo-formio pull request #172
Opened 2022-01-04 10:21 UTC by lieblinger

Details see:
https://github.com/novacode-nl/odoo-formio/pull/134
https://github.com/novacode-nl/odoo-formio/pull/72

2022-01-05 07:14 UTC, bobslee commented on formio_component/models/formio_component.py
> +        return self.search([
What in case multiple component records shall be returned?
Maybe logger.error and raise an error?

2022-01-05 07:18 UTC, bobslee commented on formio_component/models/formio_component.py
> +    def _compute_display_name(self):
Suggestion:
Would be less code and Odoo-way to implement the `name_get` function.
So you can also remove the field `display_name` (with its other occurrences).

See example: https://github.com/lieblinger/odoo-formio/blob/14.0-mail/formio/models/formio_form.py#L281

2022-01-05 07:26 UTC, bobslee commented on formio/controllers/main.py
> +        if post['data'].get('submit') and not post['data'].get('saveDraft'):
This check (if) could be tricky (also in the future).
Can't this reflect the `vals['state'] == FORM_STATE_COMPLETE`, set above (line 200) ?
So basically you could change to:

```
if vals.get('state') == FORM_STATE_COMPLETE:
    form.after_submit()

2022-01-05 07:27 UTC, bobslee commented on formio_component/__manifest__.py
> +    'version': '0.2',
Already version `0.2` ?
I suppose you've a `0.1` in other Odoo version?

2022-01-05 07:28 UTC, bobslee commented on formio_component/models/formio_component.py
> +
Please remove the empty lines, after every field definition.

2022-01-05 07:38 UTC, bobslee commented on formio_component/models/formio_component.py
> +            builder_records = self.env['formio.builder'].search([])
Like to read your opinion on this one.
Perhaps you've a particular reason to implement in your way. I would like to know :)

What about implementing the `synchronize_formio_components` function in the `formio.builder` model?
Also with the `ir.actions.server` (below) on the `formio.builder`.

This will bring some advantages, e.g.
- Server action in builder (action dropdown).
- Eases testing (test-ability) of the function.

I understand this would be refactoring effort, but great to have.

2022-01-05 07:39 UTC, bobslee commented on formio_component/views/formio_builder_views.xml
> +    <record id="action_synchronize_formio_components" model="ir.actions.server">
As suggested already. This server action on `formio.builder` record/object would be really great.

2022-01-05 07:40 UTC, bobslee commented on formio_mail/README.md
> +This module aims to extend the Odoo form.io stack with features, such as:
Please remove all human readable (textual) "form.io" occurrences to "Forms".
Also in screenshots.

Of course technical namings stay "formio".

2022-01-05 07:41 UTC, bobslee commented on formio_mail/__manifest__.py
> +    'version': '0.2',
Already version 0.2 ?
I suppose you've a 0.1 in other Odoo version?

2022-01-05 07:42 UTC, bobslee commented on formio_mail/__manifest__.py
> +    'depends': ['contacts', 'mail', 'formio_report_qweb', 'formio_component'],
A bit picky, but ascending ordering (convention) would be:

`'depends': ['contacts', 'mail', 'formio_component', 'formio_report_qweb'],`

2022-01-05 07:43 UTC, bobslee commented on formio_mail/models/formio_builder.py
> +
Please remove empty lines after field definitions.

2022-01-05 07:45 UTC, bobslee commented on formio_mail/static/description/index.html
> +      <img class="oe_demo oe_picture oe_screenshot" src="formio_builder_mail_settings.png">
Please change screenshot, I notice a "Form.io" term in the **Mail Template** field.
Change term to eg: "Forms: Custom Mail Template"

2022-01-05 07:47 UTC, bobslee commented
Hi @lieblinger, I did some reviewing and suggestions.
However I still need to review some files and would like to test too.
I shall proceed a.s.a.p.

2022-01-05 10:42 UTC, bobslee commented on formio/controllers/main.py
> +        if post['data'].get('submit') and not post['data'].get('saveDraft'):
Also add similar `form.after_submit` to the public controller (submit) endpoints.

1. Route function: `public_form_submit`
Approx line: https://github.com/lieblinger/odoo-formio/blob/14.0-mail/formio/controllers/public.py#L89

2. Route function: `public_form_create_submit`
Approx line: https://github.com/lieblinger/odoo-formio/blob/14.0-mail/formio/controllers/public.py#L166

2022-01-05 15:55 UTC, lieblinger commented on formio_mail/static/description/index.html
> +      <img class="oe_demo oe_picture oe_screenshot" src="formio_builder_mail_settings.png">
https://github.com/novacode-nl/odoo-formio/pull/172/commits/d024daef43008202d7780f0f2a372d40190817f0

2022-01-05 15:56 UTC, lieblinger commented on formio_mail/models/formio_builder.py
> +
https://github.com/novacode-nl/odoo-formio/pull/172/commits/c1a9af7972cc1851f868fbeec7f8fa0d67c85846

2022-01-05 15:56 UTC, lieblinger commented on formio_mail/__manifest__.py
> +    'depends': ['contacts', 'mail', 'formio_report_qweb', 'formio_component'],
https://github.com/novacode-nl/odoo-formio/pull/172/commits/019e6d74e898a73e364145f10bcacfbda19cc47f

2022-01-05 15:56 UTC, lieblinger commented on formio_mail/__manifest__.py
> +    'version': '0.2',
https://github.com/novacode-nl/odoo-formio/pull/172/commits/b1a296ea504d18046b738df90361a6898cea8962

2022-01-05 15:56 UTC, lieblinger commented on formio_mail/README.md
> +This module aims to extend the Odoo form.io stack with features, such as:
https://github.com/novacode-nl/odoo-formio/pull/172/commits/07feb118deb00d98b995fcaaf146991da335f7aa

2022-01-05 15:57 UTC, lieblinger commented on formio_component/views/formio_builder_views.xml
> +    <record id="action_synchronize_formio_components" model="ir.actions.server">
https://github.com/novacode-nl/odoo-formio/pull/172/commits/f15ecbae58deed2a251edb44ac5af9cdb5412e07

2022-01-05 15:57 UTC, lieblinger commented on formio_component/models/formio_component.py
> +            builder_records = self.env['formio.builder'].search([])
https://github.com/novacode-nl/odoo-formio/pull/172/commits/f15ecbae58deed2a251edb44ac5af9cdb5412e07

2022-01-05 15:57 UTC, lieblinger commented on formio_component/models/formio_component.py
> +
https://github.com/novacode-nl/odoo-formio/pull/172/commits/c1a9af7972cc1851f868fbeec7f8fa0d67c85846

2022-01-05 15:57 UTC, lieblinger commented on formio_component/__manifest__.py
> +    'version': '0.2',
https://github.com/novacode-nl/odoo-formio/pull/172/commits/b1a296ea504d18046b738df90361a6898cea8962

2022-01-05 15:57 UTC, lieblinger commented on formio/controllers/main.py
> +        if post['data'].get('submit') and not post['data'].get('saveDraft'):
https://github.com/novacode-nl/odoo-formio/pull/172/commits/b05e8d84de181969d7e90a68d8ff574660c7546c

2022-01-05 15:58 UTC, lieblinger commented on formio_component/models/formio_component.py
> +    def _compute_display_name(self):
https://github.com/novacode-nl/odoo-formio/pull/172/commits/1a31f9711b199077014fce8ea423996c9558b26e

2022-01-05 16:01 UTC, lieblinger commented on formio_component/models/formio_component.py
> +        return self.search([
For now all of the function using **get_component()** are passing only one builder object and one component id to it. So, this wouldn't end up in any error.

I renamed the function to make it even more clear see: https://github.com/novacode-nl/odoo-formio/pull/172/commits/a64724837050e7c2d43c5b710e061eb21668465c

Do you still want me to implement raise.error or logger.error?

2022-01-06 08:05 UTC, bobslee commented on formio/controllers/main.py
> +        if post['data'].get('submit') and not post['data'].get('saveDraft'):
Slight mistake. The Form is the model.

Fix to: res.after_submit()

2022-01-06 08:14 UTC, bobslee commented on formio_component/models/formio_component.py
> +    def _get_component(self, builder, comp_id):
Please decorate with `@api.model`, all these kinda class methods, which don't apply on a `formio.component` record/object.

2022-01-06 08:25 UTC, bobslee commented on formio_component/models/formio_builder.py
> +    def __getattr__(self, name):
Please move the `__getattr_` to the `formio_data_api` module, where it belongs  :)
Also we don't get any conflict when it's added there afterwards.

2022-01-06 08:44 UTC, bobslee commented on formio_component/models/formio_builder.py
> +    def synchronize_formio_components(self, builder_records=None):
See my important suggestion/request: https://github.com/novacode-nl/odoo-formio/commit/f15ecbae58deed2a251edb44ac5af9cdb5412e07#r63003132

2022-01-06 08:51 UTC, bobslee commented on formio_component/views/formio_builder_views.xml
> +    <record id="action_synchronize_formio_components" model="ir.actions.server">
**Sever action suggestions:**

Move to new file `data/ir_server_action.xml`

Change to apply on `formio.builder` model object. And of course, test this one.
```
<odoo>
    <record id="action_synchronize_formio_components" model="ir.actions.server">
        <field name="name">Sync Components</field>
        <field name="type">ir.actions.server</field>
        <field name="state">code</field>
        <field name="model_id" ref="model_formio_builder"/>
        <field name="binding_model_id" ref="model_formio_builder"/>
        <field name="code">
    record.synchronize_formio_components()
        </field>
    </record>
</odoo>
```

2022-01-06 08:58 UTC, bobslee commented on formio/controllers/public.py
> +            Form.after_submit()
Slight mistake. The `Form` is the model.

Fix to: `res.after_submit()`

2022-01-06 11:20 UTC, bobslee commented on formio_component/models/formio_builder.py
> +    @api.model
Good work!
But now the `@api.model` shouldn't be here, when applying on a `formio.builder` record/object.

2022-01-06 11:30 UTC, bobslee commented on formio_mail/models/formio_form.py
> +        recipients = self.builder_id.get_mail_recipients(self)
Please move (refactor) this record/object method into this `formio.form` model.
`recipients = self.get_mail_recipients()`

Whereas passing `self` as argument isn't needed anymore.

Also several methods in `formio.builder`, could be moved from `formio.builder` model to `formio.form` record/object methods, without passing `self` again.
https://github.com/lieblinger/odoo-formio/blob/14.0-mail/formio_mail/models/formio_builder.py

Check these moved methods (bodies) whether to change from `self` (was builder, now form) to `self.builder_id`.

Suggested methods for move to `formio.form` model:
- `_get_recipients_from_component`
- `get_mail_recipients`

2022-01-06 13:32 UTC, bobslee commented on formio_component/models/formio_builder.py
> +# Copyright Nova Code (http://www.novacode.nl)
I analyzed and changed both models `formio_builder.py` and `formio_form.py`.
Please replace complete `formio_builder.py` file with:

```
# Copyright Nova Code (http://www.novacode.nl)
# See LICENSE file for full licensing details.

import logging

from odoo import fields, models, api, tools, _

_logger = logging.getLogger(__name__)


class FormioBuilder(models.Model):
    _inherit = 'formio.builder'

    # ----------------------------------------------------------
    # Database
    # ----------------------------------------------------------

    mail_active = fields.Boolean(
        string='Mailings active',
        help='Check this box to send submitted forms to recipients.'
    )
    mail_recipients_ids = fields.Many2many(
        'formio.mail.recipient',
        string='Recipients'
    )
    mail_recipients_formio_component_ids = fields.Many2many(
        'formio.component',
        string='Formio Component',
        domain="[('builder_id', '=', id)]",
        help='List of formio components which should be used as source for mail recipients.'
    )
    mail_recipients_partner_ids = fields.Many2many(
        'res.partner',
        help='Use mail address from partner record.'
    )
    mail_report_id = fields.Many2one(
        'ir.actions.report',
        string="Report",
        domain=[('model', '=', 'formio.form')]
    )
    mail_template_id = fields.Many2one(
        'mail.template',
        string='Mail Template',
        domain=[('model', '=', 'formio.form')],
        ondelete='restrict',
        help='This field contains the template of the mail that will be automatically sent'
    )

    def _get_recipients_from_record(self):
        """
        Get's all mail recipients from res.partner and formio.mail.recipient.

        :return array: With mail recipients in a dictionary.
        """
        res = []
        for record in self.mail_recipients_partner_ids:
            mail = tools.email_split_and_format(record.email)
            mail_values = {}
            if mail:
                mail_values['recipient'] = mail[0]
            if record.lang:
                mail_values['lang'] = record.lang
            res.append(mail_values)
        for record in builder.mail_recipients_ids:
            mail = tools.email_split_and_format(record.email)
            mail_values = {}
            if mail:
                mail_values['recipient'] = mail[0]
            res.append(mail_values)
        return res

    def _get_component_mail(self, component):
        """
        Get's the value from a supported formio.component.
        Supported components are:
             - datagrid
             - email
             - select
             - selectboxes
             - textfield

        :param obj component: Takes a formio component object.
        :return array: With the value of the desired component.
        """
        res = []
        if component.type == 'datagrid':
            for row in component.rows:
                for obj in row:
                    inner_component = row[obj]['_object']
                    res.extend(self._get_component_mail(inner_component))
            return res
        elif component.type == 'selectboxes':
            for key, value in component.value.items():
                if value:
                    res.append(key)
            return res
        elif component.type is 'email' or 'select' or 'textfield':
            res.append(component.value)
            return res
        return res
```

2022-01-06 13:34 UTC, bobslee commented on formio_mail/models/formio_builder.py
> +# Copyright Nova Code (http://www.novacode.nl)
Suggestions to improve by record/object implementation.

I checked both model files.
-  `formio_mail/models/formio_builder.py`
-  `formio_mail/models/formio_form.py`

Replace all code in `formio_mail/models/formio_builder.py` with:

```
# Copyright Nova Code (http://www.novacode.nl)
# See LICENSE file for full licensing details.

import logging

from odoo import fields, models, api, tools, _

_logger = logging.getLogger(__name__)


class FormioBuilder(models.Model):
    _inherit = 'formio.builder'

    # ----------------------------------------------------------
    # Database
    # ----------------------------------------------------------

    mail_active = fields.Boolean(
        string='Mailings active',
        help='Check this box to send submitted forms to recipients.'
    )
    mail_recipients_ids = fields.Many2many(
        'formio.mail.recipient',
        string='Recipients'
    )
    mail_recipients_formio_component_ids = fields.Many2many(
        'formio.component',
        string='Formio Component',
        domain="[('builder_id', '=', id)]",
        help='List of formio components which should be used as source for mail recipients.'
    )
    mail_recipients_partner_ids = fields.Many2many(
        'res.partner',
        help='Use mail address from partner record.'
    )
    mail_report_id = fields.Many2one(
        'ir.actions.report',
        string="Report",
        domain=[('model', '=', 'formio.form')]
    )
    mail_template_id = fields.Many2one(
        'mail.template',
        string='Mail Template',
        domain=[('model', '=', 'formio.form')],
        ondelete='restrict',
        help='This field contains the template of the mail that will be automatically sent'
    )

    def _get_recipients_from_record(self):
        """
        Get's all mail recipients from res.partner and formio.mail.recipient.

        :return array: With mail recipients in a dictionary.
        """
        res = []
        for record in self.mail_recipients_partner_ids:
            mail = tools.email_split_and_format(record.email)
            mail_values = {}
            if mail:
                mail_values['recipient'] = mail[0]
            if record.lang:
                mail_values['lang'] = record.lang
            res.append(mail_values)
        for record in builder.mail_recipients_ids:
            mail = tools.email_split_and_format(record.email)
            mail_values = {}
            if mail:
                mail_values['recipient'] = mail[0]
            res.append(mail_values)
        return res

    def _get_component_mail(self, component):
        """
        Get's the value from a supported formio.component.
        Supported components are:
             - datagrid
             - email
             - select
             - selectboxes
             - textfield

        :param obj component: Takes a formio component object.
        :return array: With the value of the desired component.
        """
        res = []
        if component.type == 'datagrid':
            for row in component.rows:
                for obj in row:
                    inner_component = row[obj]['_object']
                    res.extend(self._get_component_mail(inner_component))
            return res
        elif component.type == 'selectboxes':
            for key, value in component.value.items():
                if value:
                    res.append(key)
            return res
        elif component.type is 'email' or 'select' or 'textfield':
            res.append(component.value)
            return res
        return res
```

2022-01-06 13:35 UTC, bobslee commented on formio_mail/models/formio_form.py
> +# Copyright Nova Code (http://www.novacode.nl)
Suggestions to improve by record/object implementation.

I checked both model files.
-  `formio_mail/models/formio_builder.py`
-  `formio_mail/models/formio_form.py`

Replace all code in `formio_mail/models/formio_form.py` with:

```
# Copyright Nova Code (http://www.novacode.nl)
# See LICENSE file for full licensing details.

import base64

from odoo import api, fields, models, tools, _
from odoo.exceptions import UserError


class Form(models.Model):
    _inherit = 'formio.form'

    def get_mail_recipients(self):
        """
        This function collects all mail recipients from form components
        and database records.
        """
        res = []
        res.extend(self.builder_id._get_recipients_from_record())
        res.extend(self._get_recipients_from_component())
        return res

    def _get_recipients_from_component(self):
        """
        Computes all formio.components specified in the mail_recipients_formio_component_ids field.
        :param record formio.form: Form record to get the component values from.
        :return array: With mail recipients in a dictionary.
        """
        values = []
        result = []
        components = self.builder_id.mail_recipients_formio_component_ids
        for comp in components:
            if comp.key not in self._formio.input_components.keys():
                continue
            comp_obj = self._formio.input_components[comp.key]
            values.extend(self._get_component_mail(comp_obj))
        for v in values:
            mail = tools.email_split_and_format(v)
            if mail:
                result.append({'recipient': mail[0]})
        return result

    def after_submit(self):
        super(Form, self).after_submit()
        if self.builder_id.mail_active:
            self.send_mail()

    def send_mail(self):
        self.ensure_one()
        template = self.builder_id.mail_template_id
        recipients = self.get_mail_recipients()
        attachment_ids = self.generate_attachment()
        context = self._context

        if not template or not attachment_ids:
            return

        if 'lang' in context:
            lang = context['lang']
        elif 'lang' not in context and 'uid' in context:
            lang = self.env['res.users'].browse(context['uid']).lang
        elif 'lang' not in context and 'uid' not in context:
            lang = self.env['res.users'].browse(self.write_uid).lang
        else:
            raise UserError("The form can't be loaded. No (user) language was set.")

        for mail_values in recipients:
            if 'lang' in mail_values:
                lang = mail_values['lang']
            template.with_context(lang=lang).send_mail(
                self.id,
                force_send=True,
                email_values={
                    'email_to': mail_values['recipient'],
                    'attachment_ids': [attachment.id for attachment in attachment_ids]
                }
            )

    def generate_attachment(self):
        content, content_type = self.builder_id.mail_report_id._render(self.ids)
        attachment_name = '%s - %s' % (_('Form'), self.title)
        return self.env['ir.attachment'].create({
            'name': attachment_name,
            'type': 'binary',
            'datas': base64.encodebytes(content),
            'res_model': self._name,
            'res_id': self.id,
        })
```

2022-01-06 13:51 UTC, lieblinger commented
> 

Which line should I remove?

2022-01-06 13:51 UTC, bobslee commented on formio_component/models/formio_builder.py
> +    @api.model
Changes:
- Remove `@api.model` 
- Domain: `self.ids` to `self.id`

2022-01-06 13:54 UTC, bobslee commented on formio_component/models/formio_builder.py
> +    @api.model
Remove `@api.model` from methods (due to other refactoring by suggestions).
- _compare_components
- _write_components
- _update_components
- _delete_components

And of course, test please :)

Seems you're (PR) almost ready!

2022-01-06 14:00 UTC, bobslee commented on formio_component/models/formio_builder.py
> +            ("builder_id", 'in', self.id),
Woops, domain expression should be "=" instead of "in":
`("builder_id", '=', self.id),`

2022-01-06 14:00 UTC, lieblinger commented on formio_component/models/formio_builder.py
> +            ("builder_id", 'in', self.id),
Already resolved in my latest commit :+1:

2022-01-06 14:01 UTC, bobslee commented on formio_component/models/formio_builder.py
> +            ("builder_id", 'in', self.id),
You quicker, done!

2022-01-06 14:02 UTC, bobslee commented on formio_data_api/models/formio_builder.py
> +    def __getattr__(self, name):
I need to review this one later. Keep you posted.

2022-01-06 14:07 UTC, bobslee commented on formio_component/models/formio_builder.py
> +        if vals.get('schema'):
IMHO suggestions to improve. Either or both could be usable.

(1) Would be better if there's a (boolean) checkbox on the Builder,
whether to synchronize the components.
This in case an error (eg. in code) occurs, one can disable the synchronize and still can use the Form builder.

(2) Server action to manually synchronize components.
Which of course doesn't obtain the checkbox mentoined above.
The server action can also be used in a Cron (scheduled action). Easy to manually configure, not in module.

2022-01-06 14:14 UTC, lieblinger commented on formio_component/models/formio_builder.py
> +        if vals.get('schema'):
(1) This is a good idea! Where should we place this checkbox?
(2) We already have a server action (see. (https://github.com/lieblinger/odoo-formio/blob/14.0-mail/formio_component/data/ir_server_action.xml)) is this enough?

2022-01-06 14:24 UTC, bobslee commented on formio_component/models/formio_builder.py
> +        if vals.get('schema'):
> (1) This is a good idea! Where should we place this checkbox? (2) We already have a server action (see. [https://github.com/lieblinger/odoo-formio/blob/14.0-mail/formio_component/data/ir_server_action.xml](url)) is this enough?

In the _Components API_ tab, on the top please.

Also add a short info (i) text, about its aim.
Info text goes in `<div class="text=muted">`, see examples in "formio" module, in the same tab.

> (2) We already have a server action (see. https://github.com/lieblinger/odoo-formio/blob/14.0-mail/formio_component/data/ir_server_action.xml) is this enough?

Indeed, I forgot so quickly.
Is the server action already present in the "actions" dropdown of the Builder?
If not, click the "contextual menu" button in the server action and shall appear in (Builder) "actions".
Would be great if you could arrange this.

2022-01-07 14:26 UTC, bobslee requested changes
@lieblinger you've 3 pending comments before I shall test the modules.

2022-01-07 14:26 UTC, bobslee commented on formio_component/models/formio_builder.py
> +        return self.env['formio.component'].search([
We already started this topic.
Please ensure no duplicate `formio.component` records could exist (suggestions below).
So the logging and error (raise) ain't needed.

Let's first add a `limit=1` to the `search()` method. To indicate this expects 1 record object.

Implement 1 of the suggestions (constrains) below.



**(1) Implement** `@api.constrains` **my choice**

```
@api.constrains("builder_id", "component_id")
def constraint_unique_builder_component_id(self):
    res = self.search([
        ("builder_id", "=", self.builder_id.id),
        ("component_id", "=", self.component_id.id)
        ])
    if len(res) > 1:
        raise ValidationError(_('Builder and Component ID should be unique!'))
```

**(2) Implement** `_sql_constraints` in `formio.component` model

This is a database constraint, a hard blocker and also not easy to change/extend afterwards.

```
_sql_constraints = [
        ('builder_component_id_uniq', 
         'unique(builder_id, component_id)', 'Builder and Component ID should be unique!')
    ]
```

2022-01-07 16:00 UTC, lieblinger commented on formio_component/models/formio_builder.py
> +        return self.env['formio.component'].search([
I really like the first approach. Is it okay to you, if we keep the function name ( _get_component) or do you want me to rename it to constraint_unique_builder_component_id?

2022-01-07 16:05 UTC, bobslee commented on formio_component/models/formio_builder.py
> +        return self.env['formio.component'].search([
Please keep the function `_get_component`, it's really clean.
Only add the `search(... , limit=1)`.

The first approach, is just adding a new method to block duplicate component records.
So please add `@api.constrains` with method: `def constraint_unique_builder_component_id`

2022-01-07 16:13 UTC, bobslee commented on formio_component/__manifest__.py
> +    'name': 'Forms | Component',
Btw, could we name this module a bit to clarify?
For example:
- `Forms | Components Importer`
- `Forms | Components Synchronizer`
- `Forms | Components Data`
- `Forms | Components Reference`

But I really don't know a better/alternative name.

2022-01-07 16:18 UTC, bobslee commented
Thanks for the collaboration and efforts!
I shall test very soon and keep you posted!

2022-01-08 09:31 UTC, bobslee commented on formio_component/__manifest__.py
> +Forms | Component
Please remove (empty) the `description` due to WARNING:
```
2022-01-08 09:29:20,356 960 INFO fork_lieblinger odoo.modules.registry: module formio_component: creating or updating database tables 
<string>:3: (WARNING/2) Title underline too short.

Forms | Component
================
2022-01-08 09:29:20,609 960 WARNING fork_lieblinger odoo.addons.base.models.ir_module: docutils' system message present: <system_message level="2" line="3" source="<string>" type="WARNING"><paragraph>Title underline too short.</paragraph><literal_block xml:space="preserve">Forms | Component
================</literal_block></system_message> 
```

2022-01-08 09:34 UTC, bobslee commented on formio_mail/models/formio_builder.py
> +        elif component.type is 'email' or 'select' or 'textfield':
Change to:
`elif component.type in ('email', 'select', 'textfield'):`

Due to WARNING:
```
2022-01-08 09:29:21,713 960 WARNING fork_lieblinger py.warnings: /home/odoo/odoo/addons/lieblinger/odoo-formio/formio_mail/models/formio_builder.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif component.type is 'email' or 'select' or 'textfield':
```

2022-01-08 09:41 UTC, bobslee commented on formio_mail/security/ir.model.access.csv
> +access_formio_mail_recipient,access_formio_mail_recipient,model_formio_mail_recipient,formio.group_formio_admin,1,1,1,1
Duplicate `id` values here. Change to eg:

```
id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
access_formio_mail_recipient_base_user,access_formio_mail_recipient,model_formio_mail_recipient,base.group_user,1,0,0,0
access_formio_mail_recipient_formio_admin,access_formio_mail_recipient,model_formio_mail_recipient,formio.group_formio_admin,1,1,1,1
```

Error, upon install (but luckily installs):
```
2022-01-08 09:29:22,056 960 ERROR fork_lieblinger odoo.sql_db: bad query: 
            INSERT INTO ir_model_data (module, name, model, res_id, noupdate)
            VALUES ('formio_mail', 'access_formio_mail_recipient', 'ir.model.access', 278, false), ('formio_mail', 'access_formio_mail_recipient', 'ir.model.access', 279, false)
            ON CONFLICT (module, name)
            DO UPDATE SET (model, res_id, write_date) =
                (EXCLUDED.model, EXCLUDED.res_id, now() at time zone 'UTC')

ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
 
2022-01-08 09:29:22,056 960 ERROR fork_lieblinger odoo.addons.base.models.ir_model: Failed to insert ir_model_data
```

2022-01-08 09:46 UTC, bobslee commented on formio_mail/models/formio_mail_recipient.py
> +        inverse_name='mail_recipients_ids',
Fix this `Many2many` field, `inverse_name` doesn't exist.

Due to WARNING upon install:
```
2022-01-08 09:41:24,636 2563 WARNING fork_lieblinger odoo.fields: Field formio.mail.recipient.builder_ids: unknown parameter 'inverse_name', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
```

Docs:
https://www.odoo.com/documentation/14.0/developer/reference/addons/orm.html#odoo.fields.Many2many

Example:
https://github.com/odoo/odoo/blob/14.0/addons/crm/models/crm_lead.py#L123

2022-01-08 10:19 UTC, bobslee commented on formio_component/views/formio_builder_views.xml
> +    <record id="view_formio_builder_form_inherit" model="ir.ui.view">
### Suggestions to improve (IMHO):
I shared the example XML (view) below.

1. Rename group (shorter): Synchronize Components
2. Info text (eg singular "Form Builder")
3. Would be great to have a button "Components", which opens an action-window with tree, form and search views.\
(Maybe you can implement later, then please create a GitHub issue to put in backlog). 

![afbeelding](https://user-images.githubusercontent.com/328803/148640398-f27e309a-c844-4c27-8f14-0695557c78f9.png)

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright Nova Code (http://www.novacode.nl)
See LICENSE file for full licensing details. -->

<odoo>
    <record id="view_formio_builder_form_inherit" model="ir.ui.view">
        <field name="name">formio.builder.component</field>
        <field name="model">formio.builder</field>
        <field name="inherit_id" ref="formio.view_formio_builder_form"/>
        <field name="arch" type="xml">
            <xpath expr="//button[@name='action_view_formio']" position="before">
                <button name="%(action_formio_builder_components)d" type="action" string="Components"
                        context="{'default_builder_id': id, 'search_default_builder_id': id}"
                        groups="formio.group_formio_admin" icon="fa-bars"/>
            </xpath>
            <xpath expr="//page[@name='formio_components_api']/group[@name='component_value_python_code']" position="before">
                <group string="Synchronize Components" name="sync_components" colspan="2">
                    <div class="mb-2 text-muted" colspan="2">
                        <i class="fa fa-info-circle" title="info"/>
                        Components created in the Form Builder will be imported to records.<br/>
                        This enables, for example, to select Form Components in Many2one fields.
                    </div>
                    <field name="component_sync_active"/>
                </group>
            </xpath>
        </field>
    </record>
</odoo>
```

2022-01-08 11:49 UTC, bobslee commented on formio_mail/static/description/index.html
> +  <div class="oe_row oe_centeralign mb16">
Please remove the demo and info links, line 56 until 70.

2022-01-08 11:59 UTC, bobslee commented on formio_mail/models/formio_form.py
> +            template.with_context(lang=lang).send_mail(
It is not clear that an email was sent and to which email address(ses).
(screenshot: bottom arrow)

When sending a message/mail (standard Odoo) from the chatter, the envelope icon appears (screenshot: top arrow).

I analyzed a bit, but still I don't understand why the direct `send_mail()` method doesn't trigger this.
Do you have a suggestion? I think this is really important.

![afbeelding](https://user-images.githubusercontent.com/328803/148643156-68dd62bd-a2f1-461c-a68d-e2315761b99f.png)

2022-01-08 12:14 UTC, bobslee commented on formio_component/models/formio_builder.py
> +    def _write_components(self, comp_ids):
Added `KeyError` exception handling. Replace function with one below.
I tested with a very old form builder (build with older formio.js libary version), which didn't had id-s yet.
With this improvement a nice ValidationError shall be shown (screenshot below), instead of a Python exception with a traceback.

```
    def _write_components(self, comp_ids):
        """
        Writes the components with all required data to formio.component model.
        """
        for comp_id in comp_ids:
            try:
                obj = self._formio.component_ids[comp_id]
            except KeyError as e:
                msg = _('No component found with id %s in the Form Builder.\n\n'
                'Suggestion:\nOpen the Form Builder and add or edit a component (eg label, setting), which generates new component ids.') % comp_id
                raise ValidationError(msg)
            
            self.env['formio.component'].create({
                'label': obj.label,
                'component_id': obj.id,
                'key': obj.key,
                'type': obj.type,
                'builder_id': self.id,
            })
```

**NEW - Validation error**

![afbeelding](https://user-images.githubusercontent.com/328803/148643729-1f10541f-42d6-4061-88ec-b5ef714e6520.png)

2022-01-08 12:19 UTC, bobslee commented on formio_component/models/formio_builder.py
> +        if not self.component_sync_active:
I really would like to allow server-action always to synchronize the components.
Even when the `component_sync_active=False`.

This distinguishes the sync:
- automatic upon `write()`, by checking `component_sync_active`
- manual by server-action, no check needed.

2022-01-08 12:21 UTC, bobslee requested changes
I just tested and reviewed the modules.
Did some suggestions (also code) and we need to solve the `send_mail` (hidden) envelope issue.

Looks very promising! I hope we can finalize soon.

2022-01-08 15:29 UTC, bobslee commented
Can you rename the module `formio_component` to `formio_component_synchronizer`.

2022-01-10 14:25 UTC, bobslee commented
Just an idea (for the future):

It would be really impressive and versatile if Mails can be configured by `One2many` per configuration, instead of a single config (mail template, report, recipients).
So different templates and reports can be send to specific recipients.

See screenshot below,  a similar `One2many` implementation, but for the Component (assign) value API. 

![afbeelding](https://user-images.githubusercontent.com/328803/148781501-afebe670-5508-4209-a721-1c6c916bfdb4.png)

2022-02-02 16:18 UTC, bobslee commented
@lieblinger Hi, any progress with my latest suggestions? :)

2022-04-04 21:36 UTC, lieblinger commented on formio_mail/models/formio_form.py
> +            template.with_context(lang=lang).send_mail(
This is a difficult one, was also doing alot of researching but haven't found any tip.

2022-04-07 05:08 UTC, lieblinger commented
Added your suggestions and created a couple of improvements. 
Would be very happy if you could review.

2022-04-13 09:16 UTC, bobslee commented
> Added your suggestions and created a couple of improvements. Would be very happy if you could review.

Thanks, I shall review a.s.a.p.

2022-04-26 06:55 UTC, bobslee commented
Hi, I still suggested a mistake in the module name.
Could you rename to `formio_components_synchronizer` (with plural "s") ?
It would otherwise be ordered in "component" modules eg: `formio_component_recaptcha`, `formio_component_qrcode` etc.

I can review in the weekend or next week.

2022-05-06 08:06 UTC, bobslee commented
I experience an issue with the Mail Recipients (One2many), see screenshot below.
In the first line I still can select components, however not in the new (2nd) line - it's empty.
Do you also experience this?
I analyzed the code, but can't find the issue yet.

Btw, the components synchronizer works! Excellent!

![image](https://user-images.githubusercontent.com/328803/167092185-1277cbe8-0ea0-45cb-9d2f-d92ce68456f2.png)

2022-06-12 07:29 UTC, merged