11.0 mail
novacode-nl/odoo-formio pull request #72
Opened 2020-11-21 11:13 UTC by lieblinger

2020-11-23 08:18 UTC, bobslee commented on formio_mail/models/formio_builder.py
> +    mail_recipients_form = fields.Char(string='Formio Component',
@lieblinger I don't understand the use of this field yet.
Please could you explain?

2020-11-23 08:27 UTC, bobslee commented on formio_mail/models/formio_builder.py
> +            match = re.match('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$', mail)
@lieblinger I'm always careful with regexes, rather scary.

Please use Python standard library https://docs.python.org/3/library/email.utils.html
E.g. Odoo usage: https://github.com/odoo/odoo/blob/11.0/odoo/tools/mail.py#L513
Don't forget: `from email.utils import getaddresses`

Or import and use regex pattern provided by: https://github.com/odoo/odoo/blob/11.0/odoo/tools/mail.py#L429

2020-11-23 08:45 UTC, bobslee commented on formio_mail/models/formio_form.py
> +        REPORT_ID = 'formio_report_qweb.action_report_formio_form'
@lieblinger IMHO... me thinking it's even fancier to configure the report(s) to send, in the `formio.builder`.

Because (you know) there're currently 2 generic reports available. Maybe even more reports (or custom) to come...
- `report_formio_form`: https://github.com/novacode-nl/odoo-formio/blob/11.0/formio_report_qweb/report/report_formio_form.xml#L86
- `report_formio_form_assigned_user`: https://github.com/novacode-nl/odoo-formio/blob/11.0/formio_report_qweb/report/report_formio_form.xml#L92

** Implement `formio.builder` field, to register/config reports to mail:**
Below how it's done regarding the "Reports Config" tab/page, with a Many2many field, to also configure extra fields (options) for the registered Reports... like the "Show not implemented components".
https://github.com/novacode-nl/odoo-formio/blob/11.0/formio_report_qweb/models/formio_builder_report.py#L12

Checking the link above, you'll see I implemented a Many2many (field) and model for this...
```
class FormioBuilderReport(models.Model):
    _name = 'formio.builder.report'
    _description = 'Formio Builder Reports'

    builder_id = fields.Many2one('formio.builder', string='Form Builder')
    ir_actions_report_id = fields.Many2one(
        'ir.actions.report', string='Report',
        domain=[('model', '=', 'formio.form')])
    show_components_not_implemented = fields.Boolean(
        "Show not implemented components", track_visibility='onchange')
```

**Mail sending implementation**
Code regarding the mail sending can get and render the registered Reports from the `formio.builder` object.

Example (incomplete):
```
report = self.env['ir.actions.report']._get_report_from_name(report_xmlid)
if report.report_type in ['qweb-html', 'qweb-pdf']:
    result, format = report.render_qweb_pdf([self.id])
else:
    res = report.render([self.id])
    if not res:
        raise UserError(_('Unsupported report type %s found.') % report.report_type)
    result, format = res
```

2020-11-23 08:49 UTC, bobslee commented on formio/models/formio_form.py
> +    def action_submit(self):
@lieblinger please could you rename `action_submit` to e.g. `_after_submit` or `after_submit` ?
Also change the call in the `controllers/main.py` func `form_submit`. Thanks!

In Odoo conventions an `action_` often implies a user action (e.g. button click).

2020-11-23 19:24 UTC, lieblinger commented on formio_mail/models/formio_builder.py
> +    mail_recipients_form = fields.Char(string='Formio Component',
*mail_recipients_form* this field holds the name of an formio form component. If the component is submitted with a valid mail (by end user) the qweb report is also send to this recipient.

2020-11-23 20:43 UTC, lieblinger commented on formio_mail/models/formio_builder.py
> +            match = re.match('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$', mail)
Done

2020-11-23 20:44 UTC, lieblinger commented on formio_mail/models/formio_form.py
> +        REPORT_ID = 'formio_report_qweb.action_report_formio_form'
**Implement formio.builder field, to register/config reports to mail:**
Done

2020-11-23 20:45 UTC, lieblinger commented on formio/models/formio_form.py
> +    def action_submit(self):
Done

2020-12-01 16:52 UTC, bobslee commented on formio_mail/models/formio_builder.py
> +    mail_subject = fields.Char(default=lambda s: _('Form.Io - You\'ve received a Form'),
@lieblinger Like we discussed, it would be really great if you could refactor theses fields `subject`, `body` towards a `mail.template` integration.

Just a heads up, the following requirements we discussed / seems logical:
- Add a field `mail_template_id = fields.Many2one(mail.template)`
- The `mail.template` res_model (model) shall be `formio.form`
- Prepare the `mail.template` model-object with adding context for recipients etc.
- Please send mails by aggregated language from the partners (recipients).

Could you please add a demo or first common `mail.template` as module data (XML), into a file e.g:
`data/mail_template_data.xml`

2021-01-26 09:34 UTC, bobslee commented on formio_data_api/models/formio_component.py
> +    _rec_name = 'display_name'
Is there a particular reason, not to implement/override the `name_get()` method/func ?
Because the `_compute_display_name()` already calls `name_get()`.

https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L1510
https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L1515

2021-02-13 11:40 UTC, bobslee requested changes
Hi Yannick @lieblinger,

I just reviewed your PR.
This looks really amazing and excellent work!

Please could you follow-up my comments and suggestions.
I would be glad to see those changes, so I can review and merge this!

Best,
Bob

2021-02-13 11:40 UTC, bobslee commented on formio_mail/models/formio_form.py
> +                    'auto_delete': True
Why (here) delete the maill from the communication history? To save space?

This can be configured in the `mail.template`. So better leave it out here :)

![image](https://user-images.githubusercontent.com/328803/107848433-b2d95480-6df3-11eb-995e-2329909f9ffb.png)

2021-02-13 11:40 UTC, bobslee commented on formio_mail/models/formio_form.py
> +        ATTACHMENT_NAME = 'Form.io Form -' + self.title
Please change:
- variable to lowercase (not a constant)
- just `'Form'` as filename prefix
- translatable

`attachment_name = '%s - %s' % (_('Form')', self.title)`

2021-02-13 11:40 UTC, bobslee commented on formio_mail/static/description/index.html
> +    <h2 class="oe_slogan" style="color:#875A7B;"><b>Form.io Mail</b></h2>
Please change to:

``` html
<h2 class="oe_slogan" style="color:#875A7B;"><b>Forms | Mail</b></h2>
```

2021-02-13 11:40 UTC, bobslee commented on formio_mail/static/description/index.html
> +    <h3 class="oe_slogan">Send a form as pdf via mail to everyone you want</h3>
Please change to:

``` html
<h3 class="oe_slogan">Send a Form as PDF-file via mail to everyone you want</h3>
```

2021-02-13 11:40 UTC, bobslee commented on formio_mail/static/description/index.html
> +      <h4 class="oe_mb16 text-center">Let user's and admins easily send forms to colleagues, family, business partners and anyone else.</h4>
Change to:
(see also: user's **to** users)

``` html
<h4 class="oe_mb16 text-center">Let users and admins easily send Forms to colleagues, family, business partners and anyone else.</h4>
```

2021-02-13 11:40 UTC, bobslee commented on formio_mail/static/description/index.html
> +        <strong>Out-of-the-box</strong> send a form as pdf to everyone you want.
Change:

``` html
<strong>Out-of-the-box</strong> send a Form as PDF-file to everyone you want.
```

2021-02-13 11:40 UTC, bobslee commented on formio_mail/static/description/index.html
> +        User's can <strong>easily</strong> specify recipients in the form.
Change:

``` html
User's can <strong>easily</strong> specify recipients in the Form.
```

2021-02-13 11:40 UTC, bobslee commented on formio_mail/static/description/index.html
> +        Custom <strong>body and subject</strong> text for every form builder.
Change:

``` html
Custom <strong>body and subject</strong> text for every Form Builder.
```

2021-02-13 11:40 UTC, bobslee commented on formio_mail/views/formio_builder_views.xml
> +                        <field name="mail_formio_components" string="Form Components" widget="many2many_tags"/>
See also suggested change in the model:

```
<field name="mail_formio_component_ids" string="Form Components" widget="many2many_tags"/>
```

2021-02-13 11:40 UTC, bobslee commented on formio_data_api/models/formio_builder.py
> +        self.env['formio.component'].synchronize_components(self.ids)
**Fix and improvement:**

``` python
@api.multi
def write(self, vals):
    res = super(FormioBuilder, self).write(vals)
    if vals.get('schema'):
        self.env['formio.component'].synchronize_components(self.ids)
    return res 
```

2021-02-13 11:40 UTC, bobslee commented on formio_data_api/models/formio_builder.py
> +        self.env['formio.component'].synchronize_components(self.ids)
**Question:**

Or we should only synchronize_components...
```
if vals.get('state') == 'CURRENT':
```

Then again, it would be useful to save and see the components also when (still) saving in DRAFT state.
Maybe we could implement a button on the `formio.builder` form view? Which calls a new `action_synchronize_formio_components` (which just calls the `synchronize_components`)

**Other suggestions:**

(1) Rename the `synchronize_components` to `_synchronize_formio_components`.
- Prefix underscore (_) to imply a special method/function
- Add infix `_formio_` so we won't get into troubles when Odoo core implements a `_synchronize_components`.

(2) Instead of providing `self.ids` to `_synchronize_formio_components(self.ids)`....
Could we pass just `self`, the `formio.builder` object(s) ?
This avoids the redundant query penalties which I mentoined ealier.

2021-02-14 08:14 UTC, lieblinger commented on formio_data_api/models/formio_builder.py
> +        self.env['formio.component'].synchronize_components(self.ids)
>  Maybe we could implement a button on the formio.builder form view? Which calls a new action_synchronize_formio_components (which just calls the synchronize_components)

What do you think of adding a cron which runs daily?

2021-02-14 08:17 UTC, lieblinger commented on formio_data_api/models/formio_builder.py
> +        self.env['formio.component'].synchronize_components(self.ids)
See: https://github.com/novacode-nl/odoo-formio/pull/72/commits/befb70553adab6f4b3b606c31b815457b24fee38

2021-02-14 11:17 UTC, bobslee requested changes
@lieblinger excellent improvements!

Please check, there're a few comments (questions, improvements) left.
Almost ready to merge :)

2021-02-14 11:17 UTC, bobslee commented on formio_mail/models/formio_form.py
> +            'mimetype': 'application/x-pdf'
I wonder whether this `mimetype` is needed.
Possible to test without this?

I also notice in Odoo core addons `'mimetype': 'application/pdf'`instead of `x-pdf`.

2021-02-14 11:17 UTC, bobslee commented on formio_mail/static/description/index.html
> +    <h2 class="oe_slogan" style="color:#875A7B;"><b>Form.io Mail</b></h2>
Please change to:

``` html
<h2 class="oe_slogan" style="color:#875A7B;"><b>Forms | Mail</b></h2>
```

https://github.com/lieblinger/odoo-formio/blob/11.0-mail/formio_mail/static/description/index.html#L3

2021-02-14 11:17 UTC, bobslee commented on formio_mail/views/formio_builder_views.xml
> +            <xpath expr="//page[@name='forms']" position="after">
Would be nice to get this after the (QWeb) Reports tab.

`<xpath expr="//page[@name='qweb_reports]" position="after">`

2021-02-14 13:25 UTC, bobslee approved these changes
Thanks @lieblinger !! It seems we have tackled everything.
I shall test one more time and merge afterwards.
Keep you posted.

2021-02-14 13:25 UTC, bobslee commented on formio_mail/README.md
> +# Formio Mail Extension
**Change to:**
Forms | Mail

2021-02-16 09:20 UTC, bobslee requested changes

2021-02-16 09:57 UTC, bobslee approved these changes

2021-02-17 16:22 UTC, bobslee commented
@lieblinger While testing, I stumbled on a weird bug in the Email envelope.
I hope my screenshot explains the test case.
I expected the partner in the `To (partners)` of the `mail.mail` record.

Tomorrow I proceed with testing... Maybe you already could submit a fix?

![image](https://user-images.githubusercontent.com/328803/108233676-51dbb480-7144-11eb-97dd-9aead87df6f3.png)

2021-02-17 21:11 UTC, lieblinger commented
**TODO:** Add mail recipients to chatter message.

2021-02-20 13:36 UTC, merged